# Introduction to Data Science 2021

# Week 1

## Exercise 1 | Matrix warm-up
<span style="background-color: #ccfff2"> *Note: You can find tutorials for NumPy and Pandas under 'Useful tutorials' in Moodle.*</span>

One of the most useful properties of any scientific programming language (Python with NumPy, R, Julia, etc) is that they allow us to work with matrices efficiently. Let's learn more about these features!

### 1.1 Basics

1. Let's start by creating two arrays <span style="background-color: #ccfff2"> A</span> and <span style="background-color: #ccfff2"> B</span> which each have the integers <span style="background-color: #ccfff2"> 0, 1, 2, ..., 1e7-1</span>. Use the normal arrays or lists of the programming language you are using, e.g. *list* or *[ ]* in Python.

In [17]:
A=B=list(range(0,10**7))

2. Create a function that uses a <span style="background-color: #ccfff2"> for loop</span> or equivalent to return a new array <span style="background-color: #ccfff2"> C</span>, which contains the <span style="background-color: #ccfff2"> element-wise sum of *A* and *B*</span>, e.g. C should contain the integers <span style="background-color: #ccfff2"> 0, 2, 4, etc</span>.

In [18]:
def add_with_for(A,B):
    C = []
    A=B=list(range(0,10**7))
    for x in range(0,10**7):
        C.append(A[x]+B[x])
    return C

3. Next, let's create another function that uses NumPy (or equivalent) to do the same. To try it out, allocate two arrays (e.g. using <span style="background-color: #ccfff2"> np.array</span> in NumPy) and add the arrays together using your function. Don't use loops, instead, find out how to add the two arrays directly. What do you notice in comparison to the previous function?

In [19]:
import numpy as np
C=[]
A=B=np.array(list(range(0,10**7)))
C=A+B

### 1.2 Array manipulation

<span style="background-color: #ccfff2"> *Note: for the following exercises, only use NumPy or equivalent functions. Don't use any loops.* </span>
1. Create the following array:

*[hint: <span style="background-color: #ccfff2"> np.reshape</span>]*

In [20]:
# array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
#        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
#        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
#        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
#        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
#        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
#        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
#        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
#        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
#        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [21]:
import numpy as np
a = np.arange(100).reshape((10, 10))

2. Create the following array:

In [ ]:
# array([[0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.]])

In [23]:
import numpy as np
n = 10
b = np.zeros(n*n, dtype=float)
b[1::2]=1
b = b.reshape(n, n)

3. Create the following array (D):

In [ ]:
# array([[0., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.]])

In [24]:
import numpy as np
n = 10
D = np.ones(n*n, dtype=float)
D[::11]=0
D = D.reshape(n, n)

4. Create the following array (E):

In [ ]:
# array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [0., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [25]:
import numpy as np
n = 10
E = np.ones(n*n, dtype=float)
E[9::9]=0
E = E.reshape(n, n)
E[9,9]=1

5. Call the last two matrices <span style="background-color: #ccfff2">D</span> and <span style="background-color: #ccfff2">E</span>, respectively. Show that the determinant of their product (matrix multiplication) is the same as the product of their determinants. That is calculate both <span style="background-color: #ccfff2">det(DE)</span> and <span style="background-color: #ccfff2">det(D) * det(E)</span>, and show that they are the same. Why does this hold in this instance? Does it hold in general? The product of the determinants (or the determinant of the product) should be -81.

In [26]:
# calculating the determinant of D
detD = np.linalg.det(D)
# calculating the determinant of E
detE = np.linalg.det(E)
# calculating the determinant of the product of the matrices
detproduct=np.linalg.det(np.dot(D,E))

#printing the values of the determinant of the product and the product of the determinants
print(detproduct,' = ', detD*detE, '   (approximately, ignoring rounding errors)')

# testing TRUE/FALSE to see whether Python considers the two results to be the same (rounding to eliminate small rounding errors)
when_true = round(detproduct) == round(detD*detE)
print(when_true)

-81.00000000000003  =  -81.0    (approximately, ignoring rounding errors)
True


det(DE) = det(D) * det(E) is a general property and holds for all cases when we are dealing with invertible matrices. An invertible matrix is a square matrix that has a non-zero determinant. Our two matrices E and D are square matrices with non-zero determinants, hence the property holds in their case.

### 1.3 Slicing

Array slicing is a powerful way to extract data from an array. Let's practice array slicing with the following exercises!

1. Load the [Boston housing dataset](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_boston.html). The data should be a matrix of shape <span style="background-color: #ccfff2">(506, 13)</span>, that is 506 rows and 13 columns. Use the <span style="background-color: #ccfff2">.shape</span> attribute of NumPy arrays to verify this. Here's a [description of the fields](https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.names).

In [13]:
# loading the Boston housing dataset and using .shape to verify the shape of the data matrix
import numpy as np
from sklearn.datasets import load_boston
X, y = load_boston(return_X_y=True)
print(X.shape)

(506, 13)


2. Select rows where the Crime feature <span style="background-color: #ccfff2">(CRIM)</span> is higher than 1. The first few row numbers should be <span style="background-color: #ccfff2">16, 20, 22</span> (zero-indexed). How many are there? *[hint: <span style="background-color: #ccfff2">np.where</span>]*

In [14]:
import pandas as pd

from sklearn.datasets import load_boston
boston_data =load_boston()
boston = pd.DataFrame(boston_data.data, columns=boston_data.feature_names)

# Choose entries with CRIM higher than 1
df_new = boston[boston['CRIM'] > 1]
print(df_new)

        CRIM   ZN  INDUS  CHAS    NOX     RM   AGE     DIS   RAD    TAX  \
16   1.05393  0.0   8.14   0.0  0.538  5.935  29.3  4.4986   4.0  307.0   
20   1.25179  0.0   8.14   0.0  0.538  5.570  98.1  3.7979   4.0  307.0   
22   1.23247  0.0   8.14   0.0  0.538  6.142  91.7  3.9769   4.0  307.0   
29   1.00245  0.0   8.14   0.0  0.538  6.674  87.3  4.2390   4.0  307.0   
30   1.13081  0.0   8.14   0.0  0.538  5.713  94.1  4.2330   4.0  307.0   
..       ...  ...    ...   ...    ...    ...   ...     ...   ...    ...   
483  2.81838  0.0  18.10   0.0  0.532  5.762  40.3  4.0983  24.0  666.0   
484  2.37857  0.0  18.10   0.0  0.583  5.871  41.9  3.7240  24.0  666.0   
485  3.67367  0.0  18.10   0.0  0.583  6.312  51.9  3.9917  24.0  666.0   
486  5.69175  0.0  18.10   0.0  0.583  6.114  79.8  3.5459  24.0  666.0   
487  4.83567  0.0  18.10   0.0  0.583  5.905  53.2  3.1523  24.0  666.0   

     PTRATIO       B  LSTAT  
16      21.0  386.85   6.58  
20      21.0  376.57  21.02  
22      2

3. Select the rows where the pupil-to-teach ratio <span style="background-color: #ccfff2">(PTRATIO)</span> is between 16% and 18% (exclusive). There should be **100** of these.

In [16]:
import numpy as np
import pandas as pd

from sklearn.datasets import load_boston
boston_data =load_boston()
boston = pd.DataFrame(boston_data.data, columns=boston_data.feature_names)

# rows that satisfy 16 < PTRATIO < 18
df_new2 = boston[(boston['PTRATIO'] > 16) & (boston['PTRATIO'] < 18)]
print(df_new2)

        CRIM    ZN  INDUS  CHAS    NOX     RM   AGE      DIS  RAD    TAX  \
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9   4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1   4.9671  2.0  242.0   
41   0.12744   0.0   6.91   0.0  0.448  6.770   2.9   5.7209  3.0  233.0   
42   0.14150   0.0   6.91   0.0  0.448  6.169   6.6   5.7209  3.0  233.0   
43   0.15936   0.0   6.91   0.0  0.448  6.211   6.5   5.7209  3.0  233.0   
..       ...   ...    ...   ...    ...    ...   ...      ...  ...    ...   
343  0.02543  55.0   3.78   0.0  0.484  6.696  56.4   5.7321  5.0  370.0   
344  0.03049  55.0   3.78   0.0  0.484  6.874  28.1   6.4654  5.0  370.0   
347  0.01870  85.0   4.15   0.0  0.429  6.516  27.7   8.5353  4.0  351.0   
348  0.01501  80.0   2.01   0.0  0.435  6.635  29.7   8.3440  4.0  280.0   
353  0.01709  90.0   2.02   0.0  0.410  6.728  36.1  12.1265  5.0  187.0   

     PTRATIO       B  LSTAT  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03

4. Find the mean nitric oxides concentration <span style="background-color: #ccfff2">(NOX)</span> for homes whose median price is more than 25000 USD (the target variable). It should be around **0.492**.

In [ ]:
# Jupyter notebook on how to calculate the median price:
# https://github.com/animesh-agarwal/Machine-Learning-Datasets/blob/master/boston-housing/Linear_Regression.ipynb
# Use this cell for your code

**Remember to submit your code on Moodle. You can return this Jupyter notebook (.ipynb) or .py, .R, etc depending on your programming preferences.**

## Exercise 2 | Working with text data

Next, let's look into some text data. We will be looking into Amazon reviews, and the steps needed to transform a raw dataset into a format more suitable for prediction tasts.

1. Download the automotive 5-core dataset from [here](http://jmcauley.ucsd.edu/data/amazon/). Next, you can extract the data in <span style="background-color: #ccfff2">JSON</span> format. You can also download one of the bigger ones, if you are feeling ambitious. Open the JSON file. Access the <span style="background-color: #ccfff2">reviewText</span> field, which contains the unstructured review text written by the user. 

For instance the first review reads as follows: 

*'I needed a set of jumper cables for my new car and these had good reviews and were at a good price.  They have been used a few times already and do what they are supposed to - no complaints there.What I will say is that 12 feet really isn't an ideal length.  Sure, if you pull up front bumper to front bumper they are plenty long, but a lot of times you will be beside another car or can't get really close.  Because of this, I would recommend something a little longer than 12'.Great brand - get 16' version though.'*

In [27]:
# Python program to read json file
import json

# Opening JSON file
f = open(r'C:\Users\Diana Crowe\Documents\Classes\Introduction to Data Science\Exercises\Automotive_5.json')

# returns JSON object
data = json.loads(f.read())

# Iterating through the json list
for i in data['emp_details']:
    print(i)

# Closing file
f.close()

JSONDecodeError: Extra data: line 2 column 1 (char 775)

2. Next, let's follow some steps to normalize the text data.

When dealing with natural language, it is important to notice that while, for example, the words "Copper" and "copper" are represented by two different strings, they have the same meaning. When applying statistical methods on this data, it is useful to ensure that words with the same meaning are represented by the same string.

* <span style="background-color: #ccfff2">Downcasing</span>: Let's first downcase the contents of the <span style="background-color: #ccfff2">reviewText</span> field.

Now the first review should be:

*'i needed a set of jumper cables for my new car and these had good reviews and were at a good price.  they have been used a few times already and do what they are supposed to - no complaints there.what i will say is that 12 feet really isn't an ideal length.  sure, if you pull up front bumper to front bumper they are plenty long, but a lot of times you will be beside another car or can't get really close.  because of this, i would recommend something a little longer than 12'.great brand - get 16' version though.'*

In [ ]:
# Use this cell for your code

3. Let's continue with punctuation and stop word removal. Stop words are words like "and", "the", etc. They are usually very common words that have little to do with the actual content matter. There's plenty openly available lists of stop words for almost any (natural) language.

* <span style="background-color: #ccfff2">Punctuation and stop-word removal</span>: Let's now remove all punctuation, as well as the stop words. You can find a stop word list for English, e.g. [here](http://xpo6.com/download-stop-word-list/) *(use the link for CSV download of english stop words)*.

First review at this point reads as: 

*'needed set jumper cables new car good reviews good price used few times already supposed complaints therewhat 12 feet really isnt ideal length sure pull up front bumper front bumper plenty long lot times beside another car cant really close recommend something little longer 12great brand 16 version though'*

In [ ]:
# Use this cell for your code

4. Let's continue with stemming. For example, while the words "swims" and "swim" are different strings, they both refer to swimming. [Stemming](https://en.wikipedia.org/wiki/Stemming) refers to the process of mapping words in inflected form to their base form, for instance: swims -> swim.

* <span style="background-color: #ccfff2">Stemming</span>: Apply a stemmer on the paragraphs, so that inflected forms are mapped to the base form. For example, for Python the popular natural language toolkit [nltk](http://www.nltk.org/howto/stem.html) has an easy to use stemmer. In case you are using R, you can try the [Snowball stemmer](https://www.rdocumentation.org/packages/corpus/versions/0.10.2/topics/stem_snowball).

Finally, after stemming: 

*'need set jumper cabl new car good review good price use few time alreadi suppos complaint therewhat 12 feet realli isnt ideal length sure pull up front bumper front bumper plenti long lot time besid anoth car cant realli close recommend someth littl longer 12great brand 16 version though'*

In [ ]:
# Use this cell for your code

5. Finally, filter the data by selecting reviews where the field <span style="background-color: #ccfff2">overall</span> is 4 or 5, and store the review texts in file <span style="background-color: #ccfff2">pos.txt</span>. Similarly, select reviews with rating 1 or 2 and store the reviews in file <span style="background-color: #ccfff2">neg.txt</span>. Ignore the reviews with overall rating 3. Each line in the two files should contain exactly one preprocessed review text without the rating.

In [ ]:
# Use this cell for your code

Having created two collections of positive and negative reviews, respectively, you may wish to take a quick look to see how the review texts differ between them (positive vs negative). We will be using this data later to experiment with machine learning methods.

**Remember to submit your code on Moodle. You can return this Jupyter notebook (.ipynb) or .py, .R, etc depending on your programming preferences. No need to submit the text files.**